[build]
rustflags = ["-C", "target-cpu=native"]

[target.x86_64-pc-windows-msvc]
rustflags = [
    "-Ctarget-feature=+crt-static",
]

[env] # Should always be included if ur pc based on Windows (idk why)
CFLAGS = "-DNDEBUG"