[package]
name = "zeit_bot"
version = "0.4.3-df3-tf1" # prod.result.fix-discordfix-telegramfix
authors = ["ddeeaaddllyy"]
edition = "2021"

[dependencies]
serenity = { version = "0.12", default-features = false, features = [
    "client",
    "gateway",
    "model",
    "rustls_backend",
    "cache"
] }
songbird = { version = "0.4.6", features = [
    "driver",
    "rustls",
    "serenity"
] }
tokio = { version = "1", features = ["rt", "macros", "rt-multi-thread"] }
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls", "socks"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.149"
dotenv = "0.15"

[profile.dev]
debug = 0
opt-level = 1

[profile.release]
opt-level = "z" # minimum binary size
lto = true
codegen-units = 1 # maximum optimization in release
strip = true
debug = 0

[env] # Should always be included if the proj is on Windows (idk why)
CFLAGS = "-DNDEBUG"